name: Apply semantic-release conventions to commit message

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Bump
        uses: marier-nico/pr-bump@v1.1.0
        with:
            configuration: ".github/workflows/pr_bump_config.json"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}